// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadFile(arg1:string):Promise<main.FileData>;

export function OpenFile():Promise<main.FileData>;

export function ResolveImagePath(arg1:string,arg2:string):Promise<string>;
